/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  text,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', [
  'superadmin',
  'customer',
  'instructor',
  'admin',
])
export const enum_announcements_type = pgEnum('enum_announcements_type', [
  'info',
  'alert',
  'success',
])
export const enum_announcements_target = pgEnum('enum_announcements_target', ['all', 'batch'])
export const enum_batches_status = pgEnum('enum_batches_status', [
  'upcoming',
  'open',
  'in_progress',
  'closed',
])
export const enum_workshops_status = pgEnum('enum_workshops_status', ['upcoming', 'open', 'closed'])
export const enum_quizzes_blocks_question_type = pgEnum('enum_quizzes_blocks_question_type', [
  'MCQ',
  'MSQ',
  'TEXT',
  'NUMBER',
])
export const enum_daily_quizzes_type = pgEnum('enum_daily_quizzes_type', [
  'MCQ',
  'MSQ',
  'TEXT',
  'NUMBER',
])
export const enum_problems_difficulty = pgEnum('enum_problems_difficulty', [
  'Easy',
  'Medium',
  'Hard',
])
export const enum_sessions_status = pgEnum('enum_sessions_status', [
  'WAITING',
  'ACTIVE',
  'FINISHED',
])
export const enum_sessions_mode = pgEnum('enum_sessions_mode', ['INTERACTIVE', 'DIY'])
export const enum_feedback_difficulty = pgEnum('enum_feedback_difficulty', [
  'Easy',
  'Medium',
  'Hard',
  'Very Hard',
])
export const enum_leads_status = pgEnum('enum_leads_status', [
  'New',
  'Contacted',
  'Interested',
  'Converted',
  'Closed',
])
export const enum_lessons_blocks_video_block_video_source = pgEnum(
  'enum_lessons_blocks_video_block_video_source',
  ['bunny', 'youtube', 'custom'],
)
export const enum_course_progress_status = pgEnum('enum_course_progress_status', [
  'NOT_STARTED',
  'IN_PROGRESS',
  'COMPLETED',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    displayName: varchar('display_name'),
    googleId: varchar('google_id'),
    role: enum_users_role('role').notNull().default('customer'),
    phoneNumber: varchar('phone_number'),
    batch: integer('batch_id').references(() => batches.id, {
      onDelete: 'set null',
    }),
    imageUrl: varchar('image_url'),
    streak: numeric('streak', { mode: 'number' }).default(0),
    points: numeric('points', { mode: 'number' }).default(0),
    lastQuizDate: timestamp('last_quiz_date', { mode: 'string', withTimezone: true, precision: 3 }),
    activeSessionId: varchar('active_session_id'),
    lastIP: varchar('last_i_p'),
    lastLogin: timestamp('last_login', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_google_id_idx').on(columns.googleId),
    index('users_batch_idx').on(columns.batch),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const companies = pgTable(
  'companies',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('companies_name_idx').on(columns.name),
    index('companies_updated_at_idx').on(columns.updatedAt),
    index('companies_created_at_idx').on(columns.createdAt),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const videos = pgTable(
  'videos',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    bunnyVideoId: varchar('bunny_video_id').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('videos_updated_at_idx').on(columns.updatedAt),
    index('videos_created_at_idx').on(columns.createdAt),
  ],
)

export const announcements = pgTable(
  'announcements',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    message: varchar('message').notNull(),
    type: enum_announcements_type('type').notNull().default('info'),
    target: enum_announcements_target('target').notNull().default('all'),
    batch: integer('batch_id').references(() => batches.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('announcements_batch_idx').on(columns.batch),
    index('announcements_updated_at_idx').on(columns.updatedAt),
    index('announcements_created_at_idx').on(columns.createdAt),
  ],
)

export const courses_images = pgTable(
  'courses_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('courses_images_order_idx').on(columns._order),
    index('courses_images_parent_id_idx').on(columns._parentID),
    index('courses_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [courses.id],
      name: 'courses_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const courses_pdfs = pgTable(
  'courses_pdfs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    pdf: integer('pdf_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('courses_pdfs_order_idx').on(columns._order),
    index('courses_pdfs_parent_id_idx').on(columns._parentID),
    index('courses_pdfs_pdf_idx').on(columns.pdf),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [courses.id],
      name: 'courses_pdfs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const courses = pgTable(
  'courses',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    description: jsonb('description').notNull(),
    hidden: boolean('hidden').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('courses_slug_idx').on(columns.slug),
    index('courses_updated_at_idx').on(columns.updatedAt),
    index('courses_created_at_idx').on(columns.createdAt),
  ],
)

export const batches_images = pgTable(
  'batches_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('batches_images_order_idx').on(columns._order),
    index('batches_images_parent_id_idx').on(columns._parentID),
    index('batches_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [batches.id],
      name: 'batches_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const batches_documents = pgTable(
  'batches_documents',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    document: integer('document_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('batches_documents_order_idx').on(columns._order),
    index('batches_documents_parent_id_idx').on(columns._parentID),
    index('batches_documents_document_idx').on(columns.document),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [batches.id],
      name: 'batches_documents_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const batches = pgTable(
  'batches',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    status: enum_batches_status('status').notNull().default('upcoming'),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    duration: varchar('duration'),
    price: numeric('price', { mode: 'number' }).notNull(),
    gst: numeric('gst', { mode: 'number' }).default(18),
    originalPrice: numeric('original_price', { mode: 'number' }),
    offerTitle: varchar('offer_title'),
    offerDetails: varchar('offer_details'),
    hidden: boolean('hidden').default(false),
    syllabus: jsonb('syllabus'),
    curriculum: jsonb('curriculum'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('batches_slug_idx').on(columns.slug),
    index('batches_updated_at_idx').on(columns.updatedAt),
    index('batches_created_at_idx').on(columns.createdAt),
  ],
)

export const batches_rels = pgTable(
  'batches_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    coursesID: integer('courses_id'),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('batches_rels_order_idx').on(columns.order),
    index('batches_rels_parent_idx').on(columns.parent),
    index('batches_rels_path_idx').on(columns.path),
    index('batches_rels_courses_id_idx').on(columns.coursesID),
    index('batches_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [batches.id],
      name: 'batches_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['coursesID']],
      foreignColumns: [courses.id],
      name: 'batches_rels_courses_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'batches_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const workshops_images = pgTable(
  'workshops_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('workshops_images_order_idx').on(columns._order),
    index('workshops_images_parent_id_idx').on(columns._parentID),
    index('workshops_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [workshops.id],
      name: 'workshops_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const workshops_pdfs = pgTable(
  'workshops_pdfs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    pdf: integer('pdf_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('workshops_pdfs_order_idx').on(columns._order),
    index('workshops_pdfs_parent_id_idx').on(columns._parentID),
    index('workshops_pdfs_pdf_idx').on(columns.pdf),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [workshops.id],
      name: 'workshops_pdfs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const workshops = pgTable(
  'workshops',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    status: enum_workshops_status('status').notNull().default('upcoming'),
    slug: varchar('slug').notNull(),
    description: varchar('description').notNull(),
    startDate: timestamp('start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('workshops_slug_idx').on(columns.slug),
    index('workshops_updated_at_idx').on(columns.updatedAt),
    index('workshops_created_at_idx').on(columns.createdAt),
  ],
)

export const workshops_rels = pgTable(
  'workshops_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('workshops_rels_order_idx').on(columns.order),
    index('workshops_rels_parent_idx').on(columns.parent),
    index('workshops_rels_path_idx').on(columns.path),
    index('workshops_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [workshops.id],
      name: 'workshops_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'workshops_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const quizzes_blocks_question_options = pgTable(
  'quizzes_blocks_question_options',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    option: varchar('option'),
  },
  (columns) => [
    index('quizzes_blocks_question_options_order_idx').on(columns._order),
    index('quizzes_blocks_question_options_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [quizzes_blocks_question.id],
      name: 'quizzes_blocks_question_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const quizzes_blocks_question = pgTable(
  'quizzes_blocks_question',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    type: enum_quizzes_blocks_question_type('type').default('MCQ'),
    richText: jsonb('rich_text').notNull(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    explanation: jsonb('explanation'),
    points: numeric('points', { mode: 'number' }).default(1),
    timeLimit: numeric('time_limit', { mode: 'number' }),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('quizzes_blocks_question_order_idx').on(columns._order),
    index('quizzes_blocks_question_parent_id_idx').on(columns._parentID),
    index('quizzes_blocks_question_path_idx').on(columns._path),
    index('quizzes_blocks_question_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [quizzes.id],
      name: 'quizzes_blocks_question_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const quizzes = pgTable(
  'quizzes',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    description: jsonb('description'),
    isTemplate: boolean('is_template').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('quizzes_slug_idx').on(columns.slug),
    index('quizzes_updated_at_idx').on(columns.updatedAt),
    index('quizzes_created_at_idx').on(columns.createdAt),
  ],
)

export const quizzes_texts = pgTable(
  'quizzes_texts',
  {
    id: serial('id').primaryKey(),
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    text: varchar('text'),
  },
  (columns) => [
    index('quizzes_texts_order_parent').on(columns.order, columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [quizzes.id],
      name: 'quizzes_texts_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const daily_quizzes_options = pgTable(
  'daily_quizzes_options',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    option: varchar('option'),
  },
  (columns) => [
    index('daily_quizzes_options_order_idx').on(columns._order),
    index('daily_quizzes_options_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [daily_quizzes.id],
      name: 'daily_quizzes_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const daily_quizzes = pgTable(
  'daily_quizzes',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    slug: varchar('slug').notNull(),
    batch: integer('batch_id')
      .notNull()
      .references(() => batches.id, {
        onDelete: 'set null',
      }),
    module: integer('module_id')
      .notNull()
      .references(() => course_modules.id, {
        onDelete: 'set null',
      }),
    description: jsonb('description'),
    question: jsonb('question').notNull(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    type: enum_daily_quizzes_type('type').notNull().default('MCQ'),
    explanation: jsonb('explanation'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('daily_quizzes_slug_idx').on(columns.slug),
    index('daily_quizzes_batch_idx').on(columns.batch),
    index('daily_quizzes_module_idx').on(columns.module),
    index('daily_quizzes_image_idx').on(columns.image),
    index('daily_quizzes_updated_at_idx').on(columns.updatedAt),
    index('daily_quizzes_created_at_idx').on(columns.createdAt),
  ],
)

export const daily_quizzes_texts = pgTable(
  'daily_quizzes_texts',
  {
    id: serial('id').primaryKey(),
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    text: varchar('text'),
  },
  (columns) => [
    index('daily_quizzes_texts_order_parent').on(columns.order, columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [daily_quizzes.id],
      name: 'daily_quizzes_texts_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const problems = pgTable(
  'problems',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    description: jsonb('description').notNull(),
    difficulty: enum_problems_difficulty('difficulty').notNull().default('Medium'),
    template: jsonb('template'),
    testbench: jsonb('testbench'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('problems_updated_at_idx').on(columns.updatedAt),
    index('problems_created_at_idx').on(columns.createdAt),
  ],
)

export const problems_rels = pgTable(
  'problems_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    companiesID: integer('companies_id'),
  },
  (columns) => [
    index('problems_rels_order_idx').on(columns.order),
    index('problems_rels_parent_idx').on(columns.parent),
    index('problems_rels_path_idx').on(columns.path),
    index('problems_rels_companies_id_idx').on(columns.companiesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [problems.id],
      name: 'problems_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['companiesID']],
      foreignColumns: [companies.id],
      name: 'problems_rels_companies_fk',
    }).onDelete('cascade'),
  ],
)

export const sessions = pgTable(
  'sessions',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    batch: integer('batch_id').references(() => batches.id, {
      onDelete: 'set null',
    }),
    quiz: integer('quiz_id')
      .notNull()
      .references(() => quizzes.id, {
        onDelete: 'set null',
      }),
    host: integer('host_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    status: enum_sessions_status('status').notNull().default('WAITING'),
    mode: enum_sessions_mode('mode').notNull().default('DIY'),
    totalTimeLimit: numeric('total_time_limit', { mode: 'number' }),
    endTime: timestamp('end_time', { mode: 'string', withTimezone: true, precision: 3 }),
    startedAt: timestamp('started_at', { mode: 'string', withTimezone: true, precision: 3 }),
    endedAt: timestamp('ended_at', { mode: 'string', withTimezone: true, precision: 3 }),
    currentQuestionIndex: numeric('current_question_index', { mode: 'number' }).default(-1),
    participants: jsonb('participants'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('sessions_batch_idx').on(columns.batch),
    index('sessions_quiz_idx').on(columns.quiz),
    index('sessions_host_idx').on(columns.host),
    index('sessions_updated_at_idx').on(columns.updatedAt),
    index('sessions_created_at_idx').on(columns.createdAt),
  ],
)

export const feedback_interests = pgTable(
  'feedback_interests',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    interest: varchar('interest'),
  },
  (columns) => [
    index('feedback_interests_order_idx').on(columns._order),
    index('feedback_interests_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [feedback.id],
      name: 'feedback_interests_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const feedback = pgTable(
  'feedback',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    event: varchar('event').notNull(),
    rating: numeric('rating', { mode: 'number' }).notNull(),
    improvement: varchar('improvement'),
    additionalComments: varchar('additional_comments'),
    quizId: varchar('quiz_id'),
    sessionId: varchar('session_id'),
    difficulty: enum_feedback_difficulty('difficulty'),
    giftPreference: varchar('gift_preference'),
    contactName: varchar('contact_name'),
    contactPhone: varchar('contact_phone'),
    place: varchar('place'),
    howDidYouFindUs: varchar('how_did_you_find_us'),
    source: varchar('source').default('web'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('feedback_session_id_idx').on(columns.sessionId),
    index('feedback_updated_at_idx').on(columns.updatedAt),
    index('feedback_created_at_idx').on(columns.createdAt),
  ],
)

export const leads_lead_history = pgTable(
  'leads_lead_history',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    action: varchar('action'),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }),
    details: varchar('details'),
  },
  (columns) => [
    index('leads_lead_history_order_idx').on(columns._order),
    index('leads_lead_history_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [leads.id],
      name: 'leads_lead_history_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const leads = pgTable(
  'leads',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    phone: varchar('phone'),
    source: varchar('source'),
    status: enum_leads_status('status').default('New'),
    notes: varchar('notes'),
    place: varchar('place'),
    read: boolean('read').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('leads_updated_at_idx').on(columns.updatedAt),
    index('leads_created_at_idx').on(columns.createdAt),
  ],
)

export const course_modules = pgTable(
  'course_modules',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    description: varchar('description'),
    course: integer('course_id')
      .notNull()
      .references(() => courses.id, {
        onDelete: 'set null',
      }),
    order: numeric('order', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('course_modules_course_idx').on(columns.course),
    index('course_modules_updated_at_idx').on(columns.updatedAt),
    index('course_modules_created_at_idx').on(columns.createdAt),
  ],
)

export const course_modules_rels = pgTable(
  'course_modules_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    batchesID: integer('batches_id'),
  },
  (columns) => [
    index('course_modules_rels_order_idx').on(columns.order),
    index('course_modules_rels_parent_idx').on(columns.parent),
    index('course_modules_rels_path_idx').on(columns.path),
    index('course_modules_rels_batches_id_idx').on(columns.batchesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [course_modules.id],
      name: 'course_modules_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['batchesID']],
      foreignColumns: [batches.id],
      name: 'course_modules_rels_batches_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_blocks_rich_text_block = pgTable(
  'lessons_blocks_rich_text_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    content: jsonb('content'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('lessons_blocks_rich_text_block_order_idx').on(columns._order),
    index('lessons_blocks_rich_text_block_parent_id_idx').on(columns._parentID),
    index('lessons_blocks_rich_text_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_blocks_rich_text_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_blocks_video_block = pgTable(
  'lessons_blocks_video_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    videoSource: enum_lessons_blocks_video_block_video_source('video_source').default('bunny'),
    video: integer('video_id').references(() => videos.id, {
      onDelete: 'set null',
    }),
    bunnyVideoId: varchar('bunny_video_id'),
    url: varchar('url'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('lessons_blocks_video_block_order_idx').on(columns._order),
    index('lessons_blocks_video_block_parent_id_idx').on(columns._parentID),
    index('lessons_blocks_video_block_path_idx').on(columns._path),
    index('lessons_blocks_video_block_video_idx').on(columns.video),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_blocks_video_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_blocks_quiz_block = pgTable(
  'lessons_blocks_quiz_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    quiz: integer('quiz_id')
      .notNull()
      .references(() => quizzes.id, {
        onDelete: 'set null',
      }),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('lessons_blocks_quiz_block_order_idx').on(columns._order),
    index('lessons_blocks_quiz_block_parent_id_idx').on(columns._parentID),
    index('lessons_blocks_quiz_block_path_idx').on(columns._path),
    index('lessons_blocks_quiz_block_quiz_idx').on(columns.quiz),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_blocks_quiz_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_blocks_pdf_block = pgTable(
  'lessons_blocks_pdf_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    file: integer('file_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('lessons_blocks_pdf_block_order_idx').on(columns._order),
    index('lessons_blocks_pdf_block_parent_id_idx').on(columns._parentID),
    index('lessons_blocks_pdf_block_path_idx').on(columns._path),
    index('lessons_blocks_pdf_block_file_idx').on(columns.file),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_blocks_pdf_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_topics_resources = pgTable(
  'lessons_topics_resources',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    url: varchar('url'),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('lessons_topics_resources_order_idx').on(columns._order),
    index('lessons_topics_resources_parent_id_idx').on(columns._parentID),
    index('lessons_topics_resources_file_idx').on(columns.file),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons_topics.id],
      name: 'lessons_topics_resources_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_topics = pgTable(
  'lessons_topics',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
  },
  (columns) => [
    index('lessons_topics_order_idx').on(columns._order),
    index('lessons_topics_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_topics_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons = pgTable(
  'lessons',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    module: integer('module_id')
      .notNull()
      .references(() => course_modules.id, {
        onDelete: 'set null',
      }),
    order: numeric('order', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('lessons_module_idx').on(columns.module),
    index('lessons_updated_at_idx').on(columns.updatedAt),
    index('lessons_created_at_idx').on(columns.createdAt),
  ],
)

export const lessons_rels = pgTable(
  'lessons_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    batchesID: integer('batches_id'),
  },
  (columns) => [
    index('lessons_rels_order_idx').on(columns.order),
    index('lessons_rels_parent_idx').on(columns.parent),
    index('lessons_rels_path_idx').on(columns.path),
    index('lessons_rels_batches_id_idx').on(columns.batchesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [lessons.id],
      name: 'lessons_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['batchesID']],
      foreignColumns: [batches.id],
      name: 'lessons_rels_batches_fk',
    }).onDelete('cascade'),
  ],
)

export const course_progress = pgTable(
  'course_progress',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    course: integer('course_id').references(() => courses.id, {
      onDelete: 'set null',
    }),
    lesson: integer('lesson_id')
      .notNull()
      .references(() => lessons.id, {
        onDelete: 'set null',
      }),
    status: enum_course_progress_status('status').default('NOT_STARTED'),
    completedAt: timestamp('completed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('course_progress_user_idx').on(columns.user),
    index('course_progress_course_idx').on(columns.course),
    index('course_progress_lesson_idx').on(columns.lesson),
    index('course_progress_updated_at_idx').on(columns.updatedAt),
    index('course_progress_created_at_idx').on(columns.createdAt),
  ],
)

export const lesson_notes = pgTable(
  'lesson_notes',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    lesson: integer('lesson_id')
      .notNull()
      .references(() => lessons.id, {
        onDelete: 'set null',
      }),
    batch: integer('batch_id').references(() => batches.id, {
      onDelete: 'set null',
    }),
    content: jsonb('content').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('lesson_notes_user_idx').on(columns.user),
    index('lesson_notes_lesson_idx').on(columns.lesson),
    index('lesson_notes_batch_idx').on(columns.batch),
    index('lesson_notes_updated_at_idx').on(columns.updatedAt),
    index('lesson_notes_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    companiesID: integer('companies_id'),
    mediaID: integer('media_id'),
    videosID: integer('videos_id'),
    announcementsID: integer('announcements_id'),
    coursesID: integer('courses_id'),
    batchesID: integer('batches_id'),
    workshopsID: integer('workshops_id'),
    quizzesID: integer('quizzes_id'),
    'daily-quizzesID': integer('daily_quizzes_id'),
    problemsID: integer('problems_id'),
    sessionsID: integer('sessions_id'),
    feedbackID: integer('feedback_id'),
    leadsID: integer('leads_id'),
    'course-modulesID': integer('course_modules_id'),
    lessonsID: integer('lessons_id'),
    'course-progressID': integer('course_progress_id'),
    'lesson-notesID': integer('lesson_notes_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_companies_id_idx').on(columns.companiesID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_videos_id_idx').on(columns.videosID),
    index('payload_locked_documents_rels_announcements_id_idx').on(columns.announcementsID),
    index('payload_locked_documents_rels_courses_id_idx').on(columns.coursesID),
    index('payload_locked_documents_rels_batches_id_idx').on(columns.batchesID),
    index('payload_locked_documents_rels_workshops_id_idx').on(columns.workshopsID),
    index('payload_locked_documents_rels_quizzes_id_idx').on(columns.quizzesID),
    index('payload_locked_documents_rels_daily_quizzes_id_idx').on(columns['daily-quizzesID']),
    index('payload_locked_documents_rels_problems_id_idx').on(columns.problemsID),
    index('payload_locked_documents_rels_sessions_id_idx').on(columns.sessionsID),
    index('payload_locked_documents_rels_feedback_id_idx').on(columns.feedbackID),
    index('payload_locked_documents_rels_leads_id_idx').on(columns.leadsID),
    index('payload_locked_documents_rels_course_modules_id_idx').on(columns['course-modulesID']),
    index('payload_locked_documents_rels_lessons_id_idx').on(columns.lessonsID),
    index('payload_locked_documents_rels_course_progress_id_idx').on(columns['course-progressID']),
    index('payload_locked_documents_rels_lesson_notes_id_idx').on(columns['lesson-notesID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['companiesID']],
      foreignColumns: [companies.id],
      name: 'payload_locked_documents_rels_companies_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['videosID']],
      foreignColumns: [videos.id],
      name: 'payload_locked_documents_rels_videos_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['announcementsID']],
      foreignColumns: [announcements.id],
      name: 'payload_locked_documents_rels_announcements_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['coursesID']],
      foreignColumns: [courses.id],
      name: 'payload_locked_documents_rels_courses_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['batchesID']],
      foreignColumns: [batches.id],
      name: 'payload_locked_documents_rels_batches_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['workshopsID']],
      foreignColumns: [workshops.id],
      name: 'payload_locked_documents_rels_workshops_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['quizzesID']],
      foreignColumns: [quizzes.id],
      name: 'payload_locked_documents_rels_quizzes_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['daily-quizzesID']],
      foreignColumns: [daily_quizzes.id],
      name: 'payload_locked_documents_rels_daily_quizzes_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['problemsID']],
      foreignColumns: [problems.id],
      name: 'payload_locked_documents_rels_problems_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['sessionsID']],
      foreignColumns: [sessions.id],
      name: 'payload_locked_documents_rels_sessions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['feedbackID']],
      foreignColumns: [feedback.id],
      name: 'payload_locked_documents_rels_feedback_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['leadsID']],
      foreignColumns: [leads.id],
      name: 'payload_locked_documents_rels_leads_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['course-modulesID']],
      foreignColumns: [course_modules.id],
      name: 'payload_locked_documents_rels_course_modules_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['lessonsID']],
      foreignColumns: [lessons.id],
      name: 'payload_locked_documents_rels_lessons_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['course-progressID']],
      foreignColumns: [course_progress.id],
      name: 'payload_locked_documents_rels_course_progress_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['lesson-notesID']],
      foreignColumns: [lesson_notes.id],
      name: 'payload_locked_documents_rels_lesson_notes_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  batch: one(batches, {
    fields: [users.batch],
    references: [batches.id],
    relationName: 'batch',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_companies = relations(companies, () => ({}))
export const relations_media = relations(media, () => ({}))
export const relations_videos = relations(videos, () => ({}))
export const relations_announcements = relations(announcements, ({ one }) => ({
  batch: one(batches, {
    fields: [announcements.batch],
    references: [batches.id],
    relationName: 'batch',
  }),
}))
export const relations_courses_images = relations(courses_images, ({ one }) => ({
  _parentID: one(courses, {
    fields: [courses_images._parentID],
    references: [courses.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [courses_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_courses_pdfs = relations(courses_pdfs, ({ one }) => ({
  _parentID: one(courses, {
    fields: [courses_pdfs._parentID],
    references: [courses.id],
    relationName: 'pdfs',
  }),
  pdf: one(media, {
    fields: [courses_pdfs.pdf],
    references: [media.id],
    relationName: 'pdf',
  }),
}))
export const relations_courses = relations(courses, ({ many }) => ({
  images: many(courses_images, {
    relationName: 'images',
  }),
  pdfs: many(courses_pdfs, {
    relationName: 'pdfs',
  }),
}))
export const relations_batches_images = relations(batches_images, ({ one }) => ({
  _parentID: one(batches, {
    fields: [batches_images._parentID],
    references: [batches.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [batches_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_batches_documents = relations(batches_documents, ({ one }) => ({
  _parentID: one(batches, {
    fields: [batches_documents._parentID],
    references: [batches.id],
    relationName: 'documents',
  }),
  document: one(media, {
    fields: [batches_documents.document],
    references: [media.id],
    relationName: 'document',
  }),
}))
export const relations_batches_rels = relations(batches_rels, ({ one }) => ({
  parent: one(batches, {
    fields: [batches_rels.parent],
    references: [batches.id],
    relationName: '_rels',
  }),
  coursesID: one(courses, {
    fields: [batches_rels.coursesID],
    references: [courses.id],
    relationName: 'courses',
  }),
  usersID: one(users, {
    fields: [batches_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}))
export const relations_batches = relations(batches, ({ many }) => ({
  images: many(batches_images, {
    relationName: 'images',
  }),
  documents: many(batches_documents, {
    relationName: 'documents',
  }),
  _rels: many(batches_rels, {
    relationName: '_rels',
  }),
}))
export const relations_workshops_images = relations(workshops_images, ({ one }) => ({
  _parentID: one(workshops, {
    fields: [workshops_images._parentID],
    references: [workshops.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [workshops_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_workshops_pdfs = relations(workshops_pdfs, ({ one }) => ({
  _parentID: one(workshops, {
    fields: [workshops_pdfs._parentID],
    references: [workshops.id],
    relationName: 'pdfs',
  }),
  pdf: one(media, {
    fields: [workshops_pdfs.pdf],
    references: [media.id],
    relationName: 'pdf',
  }),
}))
export const relations_workshops_rels = relations(workshops_rels, ({ one }) => ({
  parent: one(workshops, {
    fields: [workshops_rels.parent],
    references: [workshops.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [workshops_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}))
export const relations_workshops = relations(workshops, ({ many }) => ({
  images: many(workshops_images, {
    relationName: 'images',
  }),
  pdfs: many(workshops_pdfs, {
    relationName: 'pdfs',
  }),
  _rels: many(workshops_rels, {
    relationName: '_rels',
  }),
}))
export const relations_quizzes_blocks_question_options = relations(
  quizzes_blocks_question_options,
  ({ one }) => ({
    _parentID: one(quizzes_blocks_question, {
      fields: [quizzes_blocks_question_options._parentID],
      references: [quizzes_blocks_question.id],
      relationName: 'options',
    }),
  }),
)
export const relations_quizzes_blocks_question = relations(
  quizzes_blocks_question,
  ({ one, many }) => ({
    _parentID: one(quizzes, {
      fields: [quizzes_blocks_question._parentID],
      references: [quizzes.id],
      relationName: '_blocks_question',
    }),
    image: one(media, {
      fields: [quizzes_blocks_question.image],
      references: [media.id],
      relationName: 'image',
    }),
    options: many(quizzes_blocks_question_options, {
      relationName: 'options',
    }),
  }),
)
export const relations_quizzes_texts = relations(quizzes_texts, ({ one }) => ({
  parent: one(quizzes, {
    fields: [quizzes_texts.parent],
    references: [quizzes.id],
    relationName: '_texts',
  }),
}))
export const relations_quizzes = relations(quizzes, ({ many }) => ({
  _blocks_question: many(quizzes_blocks_question, {
    relationName: '_blocks_question',
  }),
  _texts: many(quizzes_texts, {
    relationName: '_texts',
  }),
}))
export const relations_daily_quizzes_options = relations(daily_quizzes_options, ({ one }) => ({
  _parentID: one(daily_quizzes, {
    fields: [daily_quizzes_options._parentID],
    references: [daily_quizzes.id],
    relationName: 'options',
  }),
}))
export const relations_daily_quizzes_texts = relations(daily_quizzes_texts, ({ one }) => ({
  parent: one(daily_quizzes, {
    fields: [daily_quizzes_texts.parent],
    references: [daily_quizzes.id],
    relationName: '_texts',
  }),
}))
export const relations_daily_quizzes = relations(daily_quizzes, ({ one, many }) => ({
  batch: one(batches, {
    fields: [daily_quizzes.batch],
    references: [batches.id],
    relationName: 'batch',
  }),
  module: one(course_modules, {
    fields: [daily_quizzes.module],
    references: [course_modules.id],
    relationName: 'module',
  }),
  image: one(media, {
    fields: [daily_quizzes.image],
    references: [media.id],
    relationName: 'image',
  }),
  options: many(daily_quizzes_options, {
    relationName: 'options',
  }),
  _texts: many(daily_quizzes_texts, {
    relationName: '_texts',
  }),
}))
export const relations_problems_rels = relations(problems_rels, ({ one }) => ({
  parent: one(problems, {
    fields: [problems_rels.parent],
    references: [problems.id],
    relationName: '_rels',
  }),
  companiesID: one(companies, {
    fields: [problems_rels.companiesID],
    references: [companies.id],
    relationName: 'companies',
  }),
}))
export const relations_problems = relations(problems, ({ many }) => ({
  _rels: many(problems_rels, {
    relationName: '_rels',
  }),
}))
export const relations_sessions = relations(sessions, ({ one }) => ({
  batch: one(batches, {
    fields: [sessions.batch],
    references: [batches.id],
    relationName: 'batch',
  }),
  quiz: one(quizzes, {
    fields: [sessions.quiz],
    references: [quizzes.id],
    relationName: 'quiz',
  }),
  host: one(users, {
    fields: [sessions.host],
    references: [users.id],
    relationName: 'host',
  }),
}))
export const relations_feedback_interests = relations(feedback_interests, ({ one }) => ({
  _parentID: one(feedback, {
    fields: [feedback_interests._parentID],
    references: [feedback.id],
    relationName: 'interests',
  }),
}))
export const relations_feedback = relations(feedback, ({ many }) => ({
  interests: many(feedback_interests, {
    relationName: 'interests',
  }),
}))
export const relations_leads_lead_history = relations(leads_lead_history, ({ one }) => ({
  _parentID: one(leads, {
    fields: [leads_lead_history._parentID],
    references: [leads.id],
    relationName: 'leadHistory',
  }),
}))
export const relations_leads = relations(leads, ({ many }) => ({
  leadHistory: many(leads_lead_history, {
    relationName: 'leadHistory',
  }),
}))
export const relations_course_modules_rels = relations(course_modules_rels, ({ one }) => ({
  parent: one(course_modules, {
    fields: [course_modules_rels.parent],
    references: [course_modules.id],
    relationName: '_rels',
  }),
  batchesID: one(batches, {
    fields: [course_modules_rels.batchesID],
    references: [batches.id],
    relationName: 'batches',
  }),
}))
export const relations_course_modules = relations(course_modules, ({ one, many }) => ({
  course: one(courses, {
    fields: [course_modules.course],
    references: [courses.id],
    relationName: 'course',
  }),
  _rels: many(course_modules_rels, {
    relationName: '_rels',
  }),
}))
export const relations_lessons_blocks_rich_text_block = relations(
  lessons_blocks_rich_text_block,
  ({ one }) => ({
    _parentID: one(lessons, {
      fields: [lessons_blocks_rich_text_block._parentID],
      references: [lessons.id],
      relationName: '_blocks_richTextBlock',
    }),
  }),
)
export const relations_lessons_blocks_video_block = relations(
  lessons_blocks_video_block,
  ({ one }) => ({
    _parentID: one(lessons, {
      fields: [lessons_blocks_video_block._parentID],
      references: [lessons.id],
      relationName: '_blocks_videoBlock',
    }),
    video: one(videos, {
      fields: [lessons_blocks_video_block.video],
      references: [videos.id],
      relationName: 'video',
    }),
  }),
)
export const relations_lessons_blocks_quiz_block = relations(
  lessons_blocks_quiz_block,
  ({ one }) => ({
    _parentID: one(lessons, {
      fields: [lessons_blocks_quiz_block._parentID],
      references: [lessons.id],
      relationName: '_blocks_quizBlock',
    }),
    quiz: one(quizzes, {
      fields: [lessons_blocks_quiz_block.quiz],
      references: [quizzes.id],
      relationName: 'quiz',
    }),
  }),
)
export const relations_lessons_blocks_pdf_block = relations(
  lessons_blocks_pdf_block,
  ({ one }) => ({
    _parentID: one(lessons, {
      fields: [lessons_blocks_pdf_block._parentID],
      references: [lessons.id],
      relationName: '_blocks_pdfBlock',
    }),
    file: one(media, {
      fields: [lessons_blocks_pdf_block.file],
      references: [media.id],
      relationName: 'file',
    }),
  }),
)
export const relations_lessons_topics_resources = relations(
  lessons_topics_resources,
  ({ one }) => ({
    _parentID: one(lessons_topics, {
      fields: [lessons_topics_resources._parentID],
      references: [lessons_topics.id],
      relationName: 'resources',
    }),
    file: one(media, {
      fields: [lessons_topics_resources.file],
      references: [media.id],
      relationName: 'file',
    }),
  }),
)
export const relations_lessons_topics = relations(lessons_topics, ({ one, many }) => ({
  _parentID: one(lessons, {
    fields: [lessons_topics._parentID],
    references: [lessons.id],
    relationName: 'topics',
  }),
  resources: many(lessons_topics_resources, {
    relationName: 'resources',
  }),
}))
export const relations_lessons_rels = relations(lessons_rels, ({ one }) => ({
  parent: one(lessons, {
    fields: [lessons_rels.parent],
    references: [lessons.id],
    relationName: '_rels',
  }),
  batchesID: one(batches, {
    fields: [lessons_rels.batchesID],
    references: [batches.id],
    relationName: 'batches',
  }),
}))
export const relations_lessons = relations(lessons, ({ one, many }) => ({
  module: one(course_modules, {
    fields: [lessons.module],
    references: [course_modules.id],
    relationName: 'module',
  }),
  _blocks_richTextBlock: many(lessons_blocks_rich_text_block, {
    relationName: '_blocks_richTextBlock',
  }),
  _blocks_videoBlock: many(lessons_blocks_video_block, {
    relationName: '_blocks_videoBlock',
  }),
  _blocks_quizBlock: many(lessons_blocks_quiz_block, {
    relationName: '_blocks_quizBlock',
  }),
  _blocks_pdfBlock: many(lessons_blocks_pdf_block, {
    relationName: '_blocks_pdfBlock',
  }),
  topics: many(lessons_topics, {
    relationName: 'topics',
  }),
  _rels: many(lessons_rels, {
    relationName: '_rels',
  }),
}))
export const relations_course_progress = relations(course_progress, ({ one }) => ({
  user: one(users, {
    fields: [course_progress.user],
    references: [users.id],
    relationName: 'user',
  }),
  course: one(courses, {
    fields: [course_progress.course],
    references: [courses.id],
    relationName: 'course',
  }),
  lesson: one(lessons, {
    fields: [course_progress.lesson],
    references: [lessons.id],
    relationName: 'lesson',
  }),
}))
export const relations_lesson_notes = relations(lesson_notes, ({ one }) => ({
  user: one(users, {
    fields: [lesson_notes.user],
    references: [users.id],
    relationName: 'user',
  }),
  lesson: one(lessons, {
    fields: [lesson_notes.lesson],
    references: [lessons.id],
    relationName: 'lesson',
  }),
  batch: one(batches, {
    fields: [lesson_notes.batch],
    references: [batches.id],
    relationName: 'batch',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    companiesID: one(companies, {
      fields: [payload_locked_documents_rels.companiesID],
      references: [companies.id],
      relationName: 'companies',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    videosID: one(videos, {
      fields: [payload_locked_documents_rels.videosID],
      references: [videos.id],
      relationName: 'videos',
    }),
    announcementsID: one(announcements, {
      fields: [payload_locked_documents_rels.announcementsID],
      references: [announcements.id],
      relationName: 'announcements',
    }),
    coursesID: one(courses, {
      fields: [payload_locked_documents_rels.coursesID],
      references: [courses.id],
      relationName: 'courses',
    }),
    batchesID: one(batches, {
      fields: [payload_locked_documents_rels.batchesID],
      references: [batches.id],
      relationName: 'batches',
    }),
    workshopsID: one(workshops, {
      fields: [payload_locked_documents_rels.workshopsID],
      references: [workshops.id],
      relationName: 'workshops',
    }),
    quizzesID: one(quizzes, {
      fields: [payload_locked_documents_rels.quizzesID],
      references: [quizzes.id],
      relationName: 'quizzes',
    }),
    'daily-quizzesID': one(daily_quizzes, {
      fields: [payload_locked_documents_rels['daily-quizzesID']],
      references: [daily_quizzes.id],
      relationName: 'daily-quizzes',
    }),
    problemsID: one(problems, {
      fields: [payload_locked_documents_rels.problemsID],
      references: [problems.id],
      relationName: 'problems',
    }),
    sessionsID: one(sessions, {
      fields: [payload_locked_documents_rels.sessionsID],
      references: [sessions.id],
      relationName: 'sessions',
    }),
    feedbackID: one(feedback, {
      fields: [payload_locked_documents_rels.feedbackID],
      references: [feedback.id],
      relationName: 'feedback',
    }),
    leadsID: one(leads, {
      fields: [payload_locked_documents_rels.leadsID],
      references: [leads.id],
      relationName: 'leads',
    }),
    'course-modulesID': one(course_modules, {
      fields: [payload_locked_documents_rels['course-modulesID']],
      references: [course_modules.id],
      relationName: 'course-modules',
    }),
    lessonsID: one(lessons, {
      fields: [payload_locked_documents_rels.lessonsID],
      references: [lessons.id],
      relationName: 'lessons',
    }),
    'course-progressID': one(course_progress, {
      fields: [payload_locked_documents_rels['course-progressID']],
      references: [course_progress.id],
      relationName: 'course-progress',
    }),
    'lesson-notesID': one(lesson_notes, {
      fields: [payload_locked_documents_rels['lesson-notesID']],
      references: [lesson_notes.id],
      relationName: 'lesson-notes',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_announcements_type: typeof enum_announcements_type
  enum_announcements_target: typeof enum_announcements_target
  enum_batches_status: typeof enum_batches_status
  enum_workshops_status: typeof enum_workshops_status
  enum_quizzes_blocks_question_type: typeof enum_quizzes_blocks_question_type
  enum_daily_quizzes_type: typeof enum_daily_quizzes_type
  enum_problems_difficulty: typeof enum_problems_difficulty
  enum_sessions_status: typeof enum_sessions_status
  enum_sessions_mode: typeof enum_sessions_mode
  enum_feedback_difficulty: typeof enum_feedback_difficulty
  enum_leads_status: typeof enum_leads_status
  enum_lessons_blocks_video_block_video_source: typeof enum_lessons_blocks_video_block_video_source
  enum_course_progress_status: typeof enum_course_progress_status
  users_sessions: typeof users_sessions
  users: typeof users
  companies: typeof companies
  media: typeof media
  videos: typeof videos
  announcements: typeof announcements
  courses_images: typeof courses_images
  courses_pdfs: typeof courses_pdfs
  courses: typeof courses
  batches_images: typeof batches_images
  batches_documents: typeof batches_documents
  batches: typeof batches
  batches_rels: typeof batches_rels
  workshops_images: typeof workshops_images
  workshops_pdfs: typeof workshops_pdfs
  workshops: typeof workshops
  workshops_rels: typeof workshops_rels
  quizzes_blocks_question_options: typeof quizzes_blocks_question_options
  quizzes_blocks_question: typeof quizzes_blocks_question
  quizzes: typeof quizzes
  quizzes_texts: typeof quizzes_texts
  daily_quizzes_options: typeof daily_quizzes_options
  daily_quizzes: typeof daily_quizzes
  daily_quizzes_texts: typeof daily_quizzes_texts
  problems: typeof problems
  problems_rels: typeof problems_rels
  sessions: typeof sessions
  feedback_interests: typeof feedback_interests
  feedback: typeof feedback
  leads_lead_history: typeof leads_lead_history
  leads: typeof leads
  course_modules: typeof course_modules
  course_modules_rels: typeof course_modules_rels
  lessons_blocks_rich_text_block: typeof lessons_blocks_rich_text_block
  lessons_blocks_video_block: typeof lessons_blocks_video_block
  lessons_blocks_quiz_block: typeof lessons_blocks_quiz_block
  lessons_blocks_pdf_block: typeof lessons_blocks_pdf_block
  lessons_topics_resources: typeof lessons_topics_resources
  lessons_topics: typeof lessons_topics
  lessons: typeof lessons
  lessons_rels: typeof lessons_rels
  course_progress: typeof course_progress
  lesson_notes: typeof lesson_notes
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_companies: typeof relations_companies
  relations_media: typeof relations_media
  relations_videos: typeof relations_videos
  relations_announcements: typeof relations_announcements
  relations_courses_images: typeof relations_courses_images
  relations_courses_pdfs: typeof relations_courses_pdfs
  relations_courses: typeof relations_courses
  relations_batches_images: typeof relations_batches_images
  relations_batches_documents: typeof relations_batches_documents
  relations_batches_rels: typeof relations_batches_rels
  relations_batches: typeof relations_batches
  relations_workshops_images: typeof relations_workshops_images
  relations_workshops_pdfs: typeof relations_workshops_pdfs
  relations_workshops_rels: typeof relations_workshops_rels
  relations_workshops: typeof relations_workshops
  relations_quizzes_blocks_question_options: typeof relations_quizzes_blocks_question_options
  relations_quizzes_blocks_question: typeof relations_quizzes_blocks_question
  relations_quizzes_texts: typeof relations_quizzes_texts
  relations_quizzes: typeof relations_quizzes
  relations_daily_quizzes_options: typeof relations_daily_quizzes_options
  relations_daily_quizzes_texts: typeof relations_daily_quizzes_texts
  relations_daily_quizzes: typeof relations_daily_quizzes
  relations_problems_rels: typeof relations_problems_rels
  relations_problems: typeof relations_problems
  relations_sessions: typeof relations_sessions
  relations_feedback_interests: typeof relations_feedback_interests
  relations_feedback: typeof relations_feedback
  relations_leads_lead_history: typeof relations_leads_lead_history
  relations_leads: typeof relations_leads
  relations_course_modules_rels: typeof relations_course_modules_rels
  relations_course_modules: typeof relations_course_modules
  relations_lessons_blocks_rich_text_block: typeof relations_lessons_blocks_rich_text_block
  relations_lessons_blocks_video_block: typeof relations_lessons_blocks_video_block
  relations_lessons_blocks_quiz_block: typeof relations_lessons_blocks_quiz_block
  relations_lessons_blocks_pdf_block: typeof relations_lessons_blocks_pdf_block
  relations_lessons_topics_resources: typeof relations_lessons_topics_resources
  relations_lessons_topics: typeof relations_lessons_topics
  relations_lessons_rels: typeof relations_lessons_rels
  relations_lessons: typeof relations_lessons
  relations_course_progress: typeof relations_course_progress
  relations_lesson_notes: typeof relations_lesson_notes
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
