/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    videos: Video;
    courses: Course;
    batches: Batch;
    workshops: Workshop;
    quizzes: Quiz;
    'daily-quizzes': DailyQuizz;
    problems: Problem;
    sessions: Session;
    feedback: Feedback;
    leads: Lead;
    'course-modules': CourseModule;
    lessons: Lesson;
    'course-progress': CourseProgress;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    batches: BatchesSelect<false> | BatchesSelect<true>;
    workshops: WorkshopsSelect<false> | WorkshopsSelect<true>;
    quizzes: QuizzesSelect<false> | QuizzesSelect<true>;
    'daily-quizzes': DailyQuizzesSelect<false> | DailyQuizzesSelect<true>;
    problems: ProblemsSelect<false> | ProblemsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'course-modules': CourseModulesSelect<false> | CourseModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    'course-progress': CourseProgressSelect<false> | CourseProgressSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  role: 'superadmin' | 'customer' | 'instructor' | 'admin';
  phoneNumber?: string | null;
  batch?: (number | null) | Batch;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches".
 */
export interface Batch {
  id: number;
  name: string;
  /**
   * Generated from name (editable)
   */
  slug: string;
  course: (number | Course)[];
  description?: string | null;
  status: 'upcoming' | 'open' | 'in_progress' | 'closed';
  startDate?: string | null;
  endDate?: string | null;
  duration?: string | null;
  price: number;
  gst?: number | null;
  originalPrice?: number | null;
  offerTitle?: string | null;
  offerDetails?: string | null;
  instructors?: (number | User)[] | null;
  hidden?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Generated from title (editable)
   */
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  pdfs?:
    | {
        pdf?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  hidden?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  bunnyVideoId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops".
 */
export interface Workshop {
  id: number;
  title: string;
  /**
   * Generated from title (editable)
   */
  slug: string;
  description: string;
  startDate: string;
  endDate?: string | null;
  instructor?: string | null;
  price?: number | null;
  place?: string | null;
  presetCollege?: string | null;
  hidden?: boolean | null;
  instructors?: (number | User)[] | null;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  pdfs?:
    | {
        pdf?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes".
 */
export interface Quiz {
  id: number;
  title: string;
  description?: string | null;
  isTemplate?: boolean | null;
  questions?:
    | {
        type?: ('MCQ' | 'MSQ' | 'TEXT' | 'NUMBER') | null;
        richText: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image?: (number | null) | Media;
        options?:
          | {
              option?: string | null;
              id?: string | null;
            }[]
          | null;
        correctAnswers: string[];
        /**
         * Shown after the student answers.
         */
        explanation?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        points?: number | null;
        timeLimit?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'question';
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-quizzes".
 */
export interface DailyQuizz {
  id: number;
  date: string;
  batch: number | Batch;
  module: number | CourseModule;
  question: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'MCQ' | 'MSQ' | 'TEXT' | 'NUMBER';
  options?:
    | {
        option: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Select the correct option(s).
   */
  correctAnswers: string[];
  /**
   * Shown after the student answers.
   */
  explanation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-modules".
 */
export interface CourseModule {
  id: number;
  title: string;
  description?: string | null;
  course: number | Course;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problems".
 */
export interface Problem {
  id: number;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  difficulty?: ('Easy' | 'Medium' | 'Hard') | null;
  template?: string | null;
  testbench?: string | null;
  testCases?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  title: string;
  quiz: number | Quiz;
  host: number | User;
  status: 'WAITING' | 'ACTIVE' | 'FINISHED';
  mode: 'INTERACTIVE' | 'DIY';
  totalTimeLimit?: number | null;
  endTime?: string | null;
  startedAt?: string | null;
  endedAt?: string | null;
  currentQuestionIndex?: number | null;
  /**
   * Map of userId to { name, score }
   */
  participants?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  name: string;
  event: string;
  rating: number;
  improvement?: string | null;
  interests?:
    | {
        interest?: string | null;
        id?: string | null;
      }[]
    | null;
  additionalComments?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone?: string | null;
  source?: string | null;
  status?: ('New' | 'Contacted' | 'Interested' | 'Converted' | 'Closed') | null;
  notes?: string | null;
  place?: string | null;
  leadHistory?:
    | {
        action?: string | null;
        date?: string | null;
        details?: string | null;
        id?: string | null;
      }[]
    | null;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  temp_trigger?: string | null;
  title: string;
  module: number | CourseModule;
  order?: number | null;
  topics?:
    | {
        title: string;
        content?:
          | (
              | {
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'richTextBlock';
                }
              | {
                  title?: string | null;
                  videoSource?: ('bunny' | 'youtube' | 'custom') | null;
                  video?: (number | null) | Video;
                  /**
                   * Legacy field. Use "Video" relationship for new uploads.
                   */
                  bunnyVideoId?: string | null;
                  url?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'videoBlock';
                }
              | {
                  quiz: number | Quiz;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'quizBlock';
                }
              | {
                  title?: string | null;
                  file: number | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'pdfBlock';
                }
            )[]
          | null;
        resources?:
          | {
              title?: string | null;
              url?: string | null;
              file?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress".
 */
export interface CourseProgress {
  id: number;
  user: number | User;
  course?: (number | null) | Course;
  lesson: number | Lesson;
  status?: ('NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED') | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'batches';
        value: number | Batch;
      } | null)
    | ({
        relationTo: 'workshops';
        value: number | Workshop;
      } | null)
    | ({
        relationTo: 'quizzes';
        value: number | Quiz;
      } | null)
    | ({
        relationTo: 'daily-quizzes';
        value: number | DailyQuizz;
      } | null)
    | ({
        relationTo: 'problems';
        value: number | Problem;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'course-modules';
        value: number | CourseModule;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'course-progress';
        value: number | CourseProgress;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  phoneNumber?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  bunnyVideoId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  pdfs?:
    | T
    | {
        pdf?: T;
        id?: T;
      };
  hidden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches_select".
 */
export interface BatchesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  course?: T;
  description?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  duration?: T;
  price?: T;
  gst?: T;
  originalPrice?: T;
  offerTitle?: T;
  offerDetails?: T;
  instructors?: T;
  hidden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops_select".
 */
export interface WorkshopsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  instructor?: T;
  price?: T;
  place?: T;
  presetCollege?: T;
  hidden?: T;
  instructors?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  pdfs?:
    | T
    | {
        pdf?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes_select".
 */
export interface QuizzesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  isTemplate?: T;
  questions?:
    | T
    | {
        question?:
          | T
          | {
              type?: T;
              richText?: T;
              image?: T;
              options?:
                | T
                | {
                    option?: T;
                    id?: T;
                  };
              correctAnswers?: T;
              explanation?: T;
              points?: T;
              timeLimit?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-quizzes_select".
 */
export interface DailyQuizzesSelect<T extends boolean = true> {
  date?: T;
  batch?: T;
  module?: T;
  question?: T;
  type?: T;
  options?:
    | T
    | {
        option?: T;
        id?: T;
      };
  correctAnswers?: T;
  explanation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problems_select".
 */
export interface ProblemsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  difficulty?: T;
  template?: T;
  testbench?: T;
  testCases?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  title?: T;
  quiz?: T;
  host?: T;
  status?: T;
  mode?: T;
  totalTimeLimit?: T;
  endTime?: T;
  startedAt?: T;
  endedAt?: T;
  currentQuestionIndex?: T;
  participants?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  name?: T;
  event?: T;
  rating?: T;
  improvement?: T;
  interests?:
    | T
    | {
        interest?: T;
        id?: T;
      };
  additionalComments?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  source?: T;
  status?: T;
  notes?: T;
  place?: T;
  leadHistory?:
    | T
    | {
        action?: T;
        date?: T;
        details?: T;
        id?: T;
      };
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-modules_select".
 */
export interface CourseModulesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  course?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  temp_trigger?: T;
  title?: T;
  module?: T;
  order?: T;
  topics?:
    | T
    | {
        title?: T;
        content?:
          | T
          | {
              richTextBlock?:
                | T
                | {
                    content?: T;
                    id?: T;
                    blockName?: T;
                  };
              videoBlock?:
                | T
                | {
                    title?: T;
                    videoSource?: T;
                    video?: T;
                    bunnyVideoId?: T;
                    url?: T;
                    id?: T;
                    blockName?: T;
                  };
              quizBlock?:
                | T
                | {
                    quiz?: T;
                    id?: T;
                    blockName?: T;
                  };
              pdfBlock?:
                | T
                | {
                    title?: T;
                    file?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        resources?:
          | T
          | {
              title?: T;
              url?: T;
              file?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress_select".
 */
export interface CourseProgressSelect<T extends boolean = true> {
  user?: T;
  course?: T;
  lesson?: T;
  status?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}